image: maven:3.6.3-jdk-11

variables:
  MAVEN_CLI_OPTS: "-s ci-settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn clean install $MAVEN_CLI_OPTS 

test:
  stage: test
  script:
    - mvn test $MAVEN_CLI_OPTS 

deploy:
  stage: deploy
  script:
    - mvn deploy $MAVEN_CLI_OPTS 
  only:
    - master
    